### ISSUE TITLE
Can you explain what howling is and why it should be removed?

### ISSUE THREAD

**Issue by kimyeondu** [CARNIVAL-IITP/Acoustic_echo_cancellation#4]
Can you explain what howling is and why it should be removed?

**Comment by wndvlf96** [comment]
Howling is annoying sound and it is generated because of the closed-loop sound reinforcement system.
In this system, output of the loudspeaker leaks into the microphone recursively.

During video conferencing, howling removal is necessary because it frequently occurs when two devices are at a close distance.
This reduces speech quality of the video conference.
